name: lint-test-build-upload
on:
  push
jobs: 
  linux:
    container: quay.io/pypa/manylinux2014_x86_64
    name: "Python ${{ matrix.PYTHON }} for manylinux2014"
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Install Python."
        run: |
            yum -y install wget libffi-devel patchelf
            /opt/python/${{ matrix.PYTHON }}/bin/python -m pip install virtualenv
            /opt/python/${{ matrix.PYTHON }}/bin/python -m virtualenv .venv
      -
        name: "Install Python dependencies for packaging process."
        run: ".venv/bin/pip install -U pip pystache toml"
      -
        name: "Package mclbn256 for all supported platforms and package managers"
        run: |
            pushd publishing/
            .venv/bin/python repack.py
            popd
      -
        name: "Upload wheel file."
        run: |
            ls -halR build/
      -
        uses: actions/upload-artifact@v1
        with:
          name: "mclbn256-0.3.3-linux1-${{ matrix.PYTHON }}"
          path: publishing/build/
    strategy:
      matrix:
        PYTHON:
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310

