name: lint-test-build-upload
on:
  push
jobs:
  manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        PYTHON: ["cp37-cp37m", "cp38-cp38", "cp39-cp39"]
    name: "Python ${{ matrix.PYTHON }} for manylinux2014"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python.
        run: |
          yum -y install wget libffi-devel
          /opt/python/${{ matrix.PYTHON }}/bin/python -m pip install virtualenv
          /opt/python/${{ matrix.PYTHON }}/bin/python -m virtualenv .venv
      - name: Install Python dependencies for build process.
        run: .venv/bin/pip install -U pip setuptools wheel build
      - name: Download mcl source tree archive and extract it.
        run: |
          wget https://github.com/herumi/mcl/archive/refs/tags/v1.61.tar.gz
          tar -xvzf *.tar.gz
      - name: Build wheel file.
        run: |
          cd mcl*
          make
          ls lib
          rm lib/libmclbn256.a
          cp lib/libmclbn256.* ..
          cd ..
          cp libmclbn256.* mclbn256
          .venv/bin/python -m build

          mkdir tmpwheelhouse
          mv dist/mclbn*.whl tmpwheelhouse
          auditwheel repair tmpwheelhouse/mclbn*.whl -w wheelhouse/
      - name: Lint and test module (and compiled libsodium shared library file).
        run: |
          #.venv/bin/pip install -U pylint coverage coveralls nose
          #.venv/bin/python -m pylint rbcl # Check against linting rules.
          #.venv/bin/python rbcl/rbcl.py -v # Run doctests.
          #.venv/bin/python -m nose --cover-erase # Test using nose.
          #.venv/bin/python -m coveralls --service=github # Submit to coveralls.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload wheel file.
        run: |
           mkdir mclbn-wheelhouse
           mv wheelhouse/mclbn*.whl mclbn-wheelhouse/
      - uses: actions/upload-artifact@v1
        with:
          name: "mclbn256-0.2.0-manylinux1-${{ matrix.PYTHON }}"
          path: mclbn-wheelhouse/
